### PR TITLE
Addition of response interface

### PR DESCRIPTION
**Pull request by Krriishhhhhh**
Draft PR: #213  

All the responses from the API endpoints present in **packages/server/src/api** and **packages/server/src/api_auth** are integrated with response interfaces which are present in **lib\types\src\api-response.ts**.

### CODE REVIEW

**Comment by Krriishhhhhh** [comment]
There are some payloads whose types i coudn't find, can u help me with that @prasenjeet-symon

**Comment by prasenjeet-symon** [comment]
> There are some payloads whose types i coudn't find, can u help me with that @prasenjeet-symon

Is that API endpoint fully implemented?

**Comment by Krriishhhhhh** [comment]
Yes , except the type of some payloads everthing else is integrated

**Comment by prasenjeet-symon** [comment]
> Yes , except the type of some payloads everthing else is integrated

If that API is not documented in POSTMAN then you can leave that, we have to document the remaining API

**Comment by Krriishhhhhh** [comment]
They are documented , but i don't know how to get their types as they are some complex nested arrays .... i was using using VS Code hint feature until now to get types but it doesn't work with complex ones

**Comment by prasenjeet-symon** [comment]
> They are documented , but i don't know how to get their types as they are some complex nested arrays .... i was using using VS Code hint feature until now to get types but it doesn't work with complex ones

Ok i see .

**Comment by prasenjeet-symon** [comment]
@Krriishhhhhh Give me some time to review, there is too much code change.

**Comment by Krriishhhhhh** [comment]
Yes sure, tell me if anything needs to be changed

**Review by prasenjeet-symon — APPROVED** [review]
Well written and managed. Thanks for your contribution.

**Pull request merged**
