### PR TITLE
Fix: Implement Zod Validation for /logout API Route #137

### PR DESCRIPTION
**Pull request by Pravesh-Sudha**

### CODE REVIEW

**Review by prasenjeet-symon — APPROVED** [review]
Looks good 👍 and Safe. Thanks

**Comment by Pravesh-Sudha** [comment]
Can you guide me through the Docs part what changes are need to be done?

**Comment by prasenjeet-symon** [comment]
> Can you guide me through the Docs part what changes are need to be done?

Are you asking about the road map?

**Comment by Pravesh-Sudha** [comment]
I am talking about this particular issue, in the description, it has provided information about testing, Zod validation and Docs, I want to know a brief about the docs part like where to update the infomation

**Comment by prasenjeet-symon** [comment]
> I am talking about this particular issue, in the description, it has provided information about testing, Zod validation and Docs, I want to know a brief about the docs part like where to update the infomation

For the testing phase, please use POSTMAN on your local machine. Refer to the documentation for setting up the project locally. If all tests pass successfully, you can proceed to submit the PR. Given that the code is quite familiar and understandable to me, there's no need for extensive testing to merge the PR.

Regarding documentation, it pertains to code documentation through comments. Ensure that your code is well-documented with clear and human-readable explanations of what each section of code does.

**Comment by Pravesh-Sudha** [comment]
I think I have done my part in these 2 PR that I have Submitted, looking forward to contributing more to your Amazing Project.

**Comment by prasenjeet-symon** [comment]
> I think I have done my part in these 2 PR that I have Submitted, looking forward to contributing more to your Amazing Project.

Thank you so much for your valuable contribution! We greatly appreciate your efforts, and we're looking forward to merging more of your pull requests in the future.

If you believe in our mission and have had a positive experience with this repository, we kindly ask for your support. Please consider giving us a "like" it truly makes a significant difference and helps us immensely.

Once again, thank you for being part of our community and for your ongoing support.

**Pull request merged**
