### PR TITLE
fix setup migration issue

### PR DESCRIPTION
**Pull request by sandheep45**

### CODE REVIEW

**Comment by sandheep45** [comment]
@prasenjeet-symon this pr will fix all initial setup issue.

**Comment by prasenjeet-symon** [comment]
> @prasenjeet-symon this pr will fix all initial setup issue.

It is larger changes , i will review it in the morning. Sorry

**Comment by prasenjeet-symon** [comment]
> @prasenjeet-symon this pr will fix all initial setup issue.

Also , i have tested it with the current codebase , in totally new computer and it worked smoothly. Can you please confirm the same by doing it in new folder and deleting all the container and volume related to this. Just following the README setup instructions. It will really help us confirm where the problem is.

**Comment by sandheep45** [comment]
> > @prasenjeet-symon this pr will fix all initial setup issue.
> 
> Also , i have tested it with the current codebase , in totally new computer and it worked smoothly. Can you please confirm the same by doing it in new folder and deleting all the container and volume related to this. Just following the README setup instructions. It will really help us confirm where the problem is.

Yeah sure will do it tomorrow. I am feeling preety exhausted right now

**Comment by prasenjeet-symon** [comment]
> > > @prasenjeet-symon this pr will fix all initial setup issue.
> > 
> > 
> > Also , i have tested it with the current codebase , in totally new computer and it worked smoothly. Can you please confirm the same by doing it in new folder and deleting all the container and volume related to this. Just following the README setup instructions. It will really help us confirm where the problem is.
> 
> Yeah sure will do it tomorrow. I am feeling preety exhausted right now

Me too 😴

**Comment by sandheep45** [comment]
image

Working fine

**Comment by prasenjeet-symon** [comment]
> image
> 
> Working fine

With old codes ??. We will add few app commands.

**Comment by sandheep45** [comment]
Yes all old commands are functional now and i have added some new command also

**Comment by prasenjeet-symon** [comment]
> Yes all old commands are functional now and i have added some new command also

Ok. Thanks

**Comment by prasenjeet-symon** [comment]
@sandheep45 Stuck on a bug, will review it in a few hours.

**Comment by sandheep45** [comment]
> @sandheep45 Stuck on a bug, will review it in a few hours.

may i help you

**Comment by prasenjeet-symon** [comment]
> > @sandheep45 Stuck on a bug, will review it in a few hours.
> 
> Can i help you in anyway

Thanks so much, it is about to be completed

**Pull request closed without merging**
