### PR TITLE
Added Docker compose

### PR DESCRIPTION
**Pull request by sandheep45**

### CODE REVIEW

**Comment by prasenjeet-symon** [comment]
@sandheep45 Can we add documentation to start the DOCKER as well as the client and server in an easy-to-understand way?

**Review by prasenjeet-symon — APPROVED** [review]
Looks good and Safe.

**Comment by sandheep45** [comment]
> @sandheep45 Can we add documentation to start the DOCKER as well as the client and server in an easy-to-understand way?

Yeah we can do that

**Comment by prasenjeet-symon** [comment]
> > @sandheep45 Can we add documentation to start the DOCKER as well as the client and server in an easy-to-understand way?
> 
> Yeah we can do that

I think #95 issue is the most important one as the number of contributors are increasing and they need clear documentation on how to set up and run the project locally.

**Pull request merged**
