### PR TITLE
Resolves #89 issue of sing up page

### LINKED ISSUE #89: Create Intellectia Signup Screen Inspired by Dribbble Design
**Title**: Create Intellectia Signup Screen Inspired by Dribbble Design

**Description**:
This GitHub issue outlines the task of creating an engaging signup screen for Intellectia, inspired by a design found on Dribbble. The signup screen is a crucial component of the application's user interface and should effectively convey Intellectia's mission and branding.

**Tasks**:
1. **Design Review**:
   - [ ] Carefully analyze the Dribbble design for inspiration. You can find it [here](https://dribbble.com/shots/21469069-Attiro-Sign-Up-Page).

2. **Mockup Development**:
   - [ ] Create a design mockup of the signup screen using design tools such as Figma, Sketch, or Adobe XD. Ensure that the design aligns with Intellectia's branding and mission.

3. **HTML and CSS Implementation**:
   - [ ] Transform the design mockup into HTML and CSS code.
   - [ ] Construct the signup form, incorporating input fields for email and password, a signup button, and a Google signup option.

4. **JavaScript Functionality**:
   - [ ] Implement client-side validation for the signup form to ensure data accuracy.
   - [ ] Integrate Google Sign-In for the Google signup functionality.

5. **Integration**:
   - [ ] Place the signup screen within the Intellectia application structure, specifically in the "pages" folder under the "Authentication" section.

6. **Responsive Design**:
   - [ ] Guarantee that the signup screen is responsive and visually appealing on various devices and screen sizes.

7. **Theming**:
   - [ ] Utilize Intellectia's application theming to ensure that the signup screen seamlessly integrates with the overall look and feel of the platform.

8. **Styling**:
   - [ ] Apply styling that matches Intellectia's brand identity and effectively communicates the platform's motivation and mission.

9. **Additional Text**:
   - [ ] Include a text element to redirect users who already have an account back to the login screen, ensuring a smooth user experience for returning users.

10. **Testing**:
    - [ ] Conduct comprehensive testing of the signup screen to confirm its proper operation, including email and password validation and Google signup.

11. **Future-Proofing**:
    - [ ] While Magic Link signup is planned for the future, ensure that the design and codebase can accommodate this feature when it is introduced.

**Note**: The Dribbble design linked in step 1 serves as inspiration for the signup screen. If you have any questions or require assistance with specific aspects of this task, please feel free to seek guidance or support.

**Additional Information**:
- The successful completion of this task will result in an engaging and user-friendly signup screen that aligns with Intellectia's mission and brand identity.

### PR DESCRIPTION
**Pull request by Codensity30**
created sign up page using tailwind css

### CODE REVIEW

**Comment by prasenjeet-symon** [comment]
@Codensity30 Please upload the screenshot of the SignUp page used in the project. Thanks

**Comment by prasenjeet-symon** [comment]
> @Codensity30 Please upload the screenshot of the SignUp page used in the project. Thanks

You can upload the screenshot here. This is just for documentation

**Review by prasenjeet-symon — APPROVED** [review]
Looks awesome 👍

**Comment by Codensity30** [comment]
should I upload the screenshot here?

**Comment by prasenjeet-symon** [comment]
It looks good but the whole page is scrolling and and image is not showing. I am creating a new issue for this.

**Comment by Codensity30** [comment]
I've found the issue, I've specified some CSS using Singup.css file which target HTML tags using id's

**Comment by prasenjeet-symon** [comment]
> I've found the issue, I've specified some CSS using Singup.css file which target HTML tags using id's

Let me create a new issue for that so that you can work on that new issue. Okay

**Comment by prasenjeet-symon** [comment]
> > I've found the issue, I've specified some CSS using Singup.css file which target HTML tags using id's
> 
> Let me create a new issue for that so that you can work on that new issue. Okay

Do check #101

**Comment by Codensity30** [comment]
please add "hacktoberfest-accepted" label to the issue/PR.

**Pull request merged**
